PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX edam: <http://edamontology.org/> 
PREFIX void: <http://rdfs.org/ns/void#> 
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX SIO: <http://semanticscience.org/resource/>


#.FA files
# Information needed : size and in which subset they are


CONSTRUCT {
    

    #Sequence Set (protein) edam:data_1233
    ?URI a ?type ; 
	
	 rdfs:label ?id;
         
         #Sequence Set Id
	 edam:data_1064 ?id;
          
	 #File Name Extension .fa
	 edam:file_extension ?extension ;
	 
	 #Fasta Format edam:1929
         edam:has_format ?format ;

         #count of sequences
         SIO:SIO_000794 ?count;
	 
	 #In which dataset they are
	 oboInOwl:inSubset ?URI_DATASET;   	

	 #Other subsets --> RV11 for example
	 oboInOwl:inSubset ?subset;
	 
  }


FROM <file:toModel-test.csv>

WHERE{

 BIND (URI(CONCAT('http://bengen.com/', ?id ,"-",?dataset)) AS ?URI)
 BIND (URI(CONCAT('http://bengen.com/', ?dataset ,"-",?version)) AS ?URI_DATASET)

}
