PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX edam: <http://edamontology.org/> 
PREFIX void: <http://rdfs.org/ns/void#> 
PREFIX SIO: <http://semanticscience.org/resource/>
PREFIX doap: <http://usefulinc.com/ns/doap#>

CONSTRUCT {
  
    ?URI a ?type;
	 rdfs:label ?NAMEandVERSION;
	 edam:has_input ?URI_INPUT;
	 edam:has_output ?URI_OUTPUT ;	
         edam:has_topic ?topic.
	

   ?URI_INPUT a ?input; 
	      	
	      #Thought to be the MAXIMAL number of sequence the MSA can align. Depends on the Query.	
	      SIO:SIO_000794 ?max_count;
              edam:has_format ?input_format.
  
   ?URI_OUTPUT a ?output;
 	       edam:has_format ?output_format.
		

	 
  }

FROM <file:toModel-msa.csv>

WHERE{
 BIND (URI(CONCAT('http://bengen.com/', ?id, '-', ?version)) AS ?URI)
 BIND (URI(CONCAT('http://bengen.com/', ?input,'-',?input_format,'-', ?max_count)) AS ?URI_INPUT)
 BIND (URI(CONCAT('http://bengen.com/', ?output, '-', ?output_format)) AS ?URI_OUTPUT)
 BIND (CONCAT(?label, '-v', ?version ) AS ?NAMEandVERSION) 
}

