FROM pditommaso/dkrbase:1.2
MAINTAINER Luisa Santus <luisa.santus@hotmail.it>

RUN wget -q http://probcons.stanford.edu/probcons_v1_12.tar.gz &&\
 tar xvf probcons_v1_12.tar.gz &&\
 apt-get install probcons &&\
 rm -rf probcons_v1_12.tar.gz
 



