FROM pditommaso/dkrbase:1.2
MAINTAINER Luisa Santus <luisa.santus@hotmail.it>

RUN wget -q http://www.clustal.org/download/current/clustalw-2.1-linux-x86_64-libcppstatic.tar.gz &&\
 tar xf clustalw-2.1-linux-x86_64-libcppstatic.tar.gz &&\
 mv clustalw-2.1-linux-x86_64-libcppstatic/clustalw2 /usr/local/bin/clustalw2 &&\
 rm -rf clustalw-2.1-linux-x86_64-libcppstatic.tar.gz clustalw-2.1-linux-x86_64-libcppstatic 
 
