FROM pditommaso/dkrbase:1.2
MAINTAINER Maria Chatzou <mxatzou@gmail.com>

RUN wget -q http://www.clustal.org/omega/clustalo-1.2.0-Ubuntu-x86_64 && \
    chmod +x clustalo-1.2.0-Ubuntu-x86_64 && \
    mv clustalo-1.2.0-Ubuntu-x86_64 /usr/local/bin/clustalo
    
