FROM pditommaso/dkrbase:1.2
MAINTAINER Luisa Santus <luisa.santus@hotmail.it>

RUN wget -q http://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz &&\
 tar xf muscle3.8.31_i86linux64.tar.gz &&\ 
 mv muscle3.8.31_i86linux64 /usr/local/bin/muscle &&\
 rm -rf muscle3.8.31_i86linux64.tar.gz
 
 





