PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX edam: <http://edamontology.org/> 
PREFIX void: <http://rdfs.org/ns/void#> 
PREFIX doap: <http://usefulinc.com/ns/doap#>

CONSTRUCT {
  
    ?URI rdfs:label ?name;		
	 doap:Version ?version;
	 
  }


FROM <file:toModel-db.csv>

WHERE{
 BIND (URI(CONCAT('http://bengen.com/', ?name)) AS ?URI)

}
