PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX edam: <http://edamontology.org/> 
PREFIX bengen: <http://bengen.com/>

CONSTRUCT {
  
    ?URI a ?id;
	 rdfs:label ?label;
	 rdf:value ?value;
	 
  }


FROM <file:toModel-threshold.csv>

WHERE{
 BIND (URI(CONCAT('http://bengen.com/', ?id ,"-",?label)) AS ?URI)
}
